spring.application.name=finalproject
server.servlet.context-path=/finalproject


# DataSource ê´ë ¨ ì¤ì :
# JDBC ëë¼ì´ë² í´ëì¤ ì´ë¦
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# DB ì ì URL
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
# DB ì ì ì¬ì©ì ì´ë¦
spring.datasource.username=enum
# DB ì ì ë¹ë°ë²í¸
spring.datasource.password=enum

# JPA/Hibernateìì DDL(create, drop, truncate, alter) ìë ì¤í ì¬ë¶
spring.jpa.hibernate.ddl-auto=none

# JPA/Hibernateìì ìì±ë SQL ë¬¸ì¥ì ë¡ê·¸ë¡ ì¶ë ¥í  ë ë³´ê¸°ì¢ê² í¬ë§·í.
spring.jpa.properties.hibernate.format_sql=true
# JPA/Hibernateìì ìì±ë SQL ë¬¸ì¥ì ë¡ê·¸ë¡ ì¶ë ¥í  ë highlight(ê¸ìì).
spring.jpa.properties.hibernate.highlight_sql=true

# ë¡ê·¸ ë ë²¨(trace < debug < info < warn < error < fatal)
# Hibernateìì ìì±ë SQL ë¬¸ì¥ì ì¶ë ¥íê¸° ìí ë¡ê·¸ ë ë²¨
logging.level.org.hibernate.SQL=DEBUG
# Hibernateìì ìì±ë PreparedStatementì ë°ì¸ë© íë¼ë¯¸í°ë¥¼ ì¶ë ¥íê¸° ìí ë¡ê·¸ ë ë²¨
logging.level.org.hibernate.orm.jdbc.bind=trace